### ISSUE TITLE
Le shell rend trop vite la main

### ISSUE THREAD

**Issue by greylan** [XAMEUS/ensimag-shell#4]
J'ai rajouté un int wait_pid pour marquer le dernier process à attendre.
Le problème c'est que ce n'est pas forcément le dernier.

Par exemple: sleep 10 | echo test rend la main immédiatement.
Il faudrait réutiliser les fonctions que tu as déjà faites pour gérer une liste des pid à attendre.

@XAMEUS vu que c'est toi qui a écrit les fonctions pour bg, tu t'en charges?

**Comment by XAMEUS** [comment]
Je ne comprends pas bien le problème, il faudrait juste s'assurer de bien attendre : 
``` c
if(!l->bg && i == len_l - 1) {
    while(wait_pid) pause();
}
```
en ça : (ligne 274)
``` c
if(!l->bg) {
    while(wait_pid) pause();
}
```
Et ça marche ?

**Comment by greylan** [comment]
Désolé de ne pas avoir vu le message à temps :/
Corrigé
